import { Router } from 'express';
import * as gameController from '../controllers/gameController.js';
import { requireAuth } from '../middleware/auth.js';
const router = Router();
router.use(requireAuth);
router.get('/:sessionId/state', gameController.getState);
router.post('/:sessionId/roll', gameController.roll);
router.post('/:sessionId/buy', gameController.buy);
router.post('/:sessionId/mortgage', gameController.mortgage);
router.post('/:sessionId/end-turn', gameController.endTurn);
router.post('/:sessionId/auction/start', gameController.startAuction);
router.post('/:sessionId/auction/bid', gameController.bid);
router.post('/:sessionId/auction/finish', gameController.finishAuction);
export default router;
